"""models updated

Revision ID: e4f2e224f91b
Revises: 4efbf373ddfe
Create Date: 2023-06-21 09:30:31.248200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f2e224f91b'
down_revision = '4efbf373ddfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_signups_activities_id_activities', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_signups_activity_id_activities'), 'activities', ['activity_id'], ['id'])
        batch_op.drop_column('activities_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activities_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_signups_activity_id_activities'), type_='foreignkey')
        batch_op.create_foreign_key('fk_signups_activities_id_activities', 'activities', ['activities_id'], ['id'])
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###
